/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.matchbox.client.forms;

import de.matchbox.client.Control;
import de.matchbox.communication.MessageObject;
import de.matchbox.communication.classmodels.RoomModel;
import de.matchbox.communication.contentobjects.client.CreateRoomContentObject;
import de.matchbox.communication.contentobjects.client.JoinRoomContentObject;
import de.matchbox.communication.enumeration.MessageType;
import de.matchbox.communication.shared.abiturklassen.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Name
 */
public class FrmLobby extends javax.swing.JFrame {

    /**
     * Creates new form FrmLobby
     */
    private Control control;
    private DefaultListModel lobby;
    private RoomCreationDialog roomCreationDialog;

    public FrmLobby(Control pControl) {
        initComponents();
        this.control = pControl;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.lobby = new DefaultListModel();
        this.jConectRoom.setEnabled(false);
        this.roomCreationDialog = new RoomCreationDialog(this, true, this.control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jRoomList = new javax.swing.JList();
        jConectRoom = new javax.swing.JButton();
        jCreateRoom = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MatchBox");

        jRoomList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRoomListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jRoomList);

        jConectRoom.setText("Conect");
        jConectRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConectRoomActionPerformed(evt);
            }
        });

        jCreateRoom.setText("Create Room");
        jCreateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jConectRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCreateRoom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConectRoom)
                    .addComponent(jCreateRoom))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jConectRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConectRoomActionPerformed
        if (!jRoomList.isSelectionEmpty()) {
            this.control.send(new MessageObject(MessageType.JOIN_ROOM, new JoinRoomContentObject(((RoomModel) (jRoomList.getSelectedValue())).getId())));
        }
    }//GEN-LAST:event_jConectRoomActionPerformed

    private void jCreateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateRoomActionPerformed

        roomCreationDialog.setVisible(true);

    }//GEN-LAST:event_jCreateRoomActionPerformed

    private void jRoomListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRoomListMouseClicked
        if (!jRoomList.isSelectionEmpty()) {
            jConectRoom.setEnabled(true);
        }
    }//GEN-LAST:event_jRoomListMouseClicked
    public void setRooms(List rooms) {
        //List voller Raeume. Muss hier noch geaendert werden
        //jList1.setListData(rooms.entrySet().toArray());
        rooms.toFirst();
        while (rooms.hasAccess()) {
            lobby.addElement((RoomModel) rooms.getObject());
            rooms.next();
        }

        jRoomList.setModel(lobby);

    }

    public void createRoom(String pName) {
        this.control.send(new MessageObject(MessageType.CREATE_ROOM, new CreateRoomContentObject(pName)));
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jConectRoom;
    private javax.swing.JButton jCreateRoom;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JList jRoomList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
